name: Code label

on:
  push:
    branches: [ 'master' ]

jobs:
  analysis:
    name: code label
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
        env:
          fail-fast: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "highest"

      - name: Psalm
        run: vendor/bin/psalm --stats --output-format=github --shepherd
